[project]
name = "open-filament-database"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "iniconfig>=2.3.0",
    "jsonschema>=4.25.1",
    "pillow>=12.0.0",
    "pydantic>=2.12.3",
    "pydantic2zod>=0.1.1",
]
