name: Validate data
on:
  pull_request:
    paths:
      - 'data/**'
      - 'stores/**'
      - 'schemas/**'
      - 'data_validator.py'
      - 'db_serializer.py'
      - 'requirements.txt'
  push:
    branches: [ main ]
    paths:
      - 'data/**'
      - 'stores/**'
      - 'schemas/**'
      - 'data_validator.py'
      - 'db_serializer.py'
      - 'requirements.txt'
  workflow_dispatch:

jobs:
  validate_data:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        name: [ json-files, folder-names, store-ids ]
    name: Validate data - ${{ matrix.name }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Validate data
        run: python data_validator.py --${{ matrix.name }}
